import Head from 'next/head'
import '../../node_modules/bootstrap-icons/font/bootstrap-icons.css'
import Navbar from './Components/Navbar'
import Section from './Components/Section'
import Services from './Components/Services'
import Cards from './Components/Cards'
import Contact from './Components/Contact'
import Footer from './Components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>IRCTC Next Generation eTicketing System</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="shortcut icon" href="https://www.irctc.co.in/nget/assets/images/logo.png" type="image/x-icon" />

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      </Head>
      <main>
        <Navbar />
        <Section />
        <Services />
        <Cards />
        <Contact />
        <Footer />
      </main>
    </>
  )
}
